project:
  type: website
  output-dir: docs

website:
  title: "Benedikt Schmid"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      
        
bibliography: publications.bib

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

