---
title: "Publications"
format:
  html:
    toc: true
---

```{r}
#| echo: false
#| output: false


library(here)
library(tidyverse)

```

## my own work
```{r}
#| echo: false
#| results: asis

readRDS(here("source", "publication_list_firstlast.rds")) |>
  mutate(AF = str_replace(AF, "Benedikt Schmid", "<span style='color: #0073e6;'>Benedikt Schmid</span>")) |>
  glue::glue_data(
    "1. {AF}<br>",
    "**{TI}**<br> *{SO}* ({PY_IS}). ",
    "DOI: <a href='https://doi.org/{DI}' target='_blank'>{DI}</a>. ",
    "PMID: {PMID}.<p>",
    ""
  ) |>
  paste(collapse = "\n") |>
  knitr::asis_output()
```

## contributing to the work of others

```{r}
#| echo: false
#| results: asis

readRDS(here("source", "publication_list_all.rds")) |>
  mutate(AF = str_replace(AF, "Benedikt Schmid", "<span style='color: #0073e6;'>Benedikt Schmid</span>")) |>
  glue::glue_data(
    "1. {AF}<br>",
    "**{TI}**<br> *{SO}* ({PY_IS}). ",
    "DOI: <a href='https://doi.org/{DI}' target='_blank'>{DI}</a>. ",
    "PMID: {PMID}.<p>",
    ""
  ) |>
  paste(collapse = "\n") |>
  knitr::asis_output()
```